#include "mainwindow.h"
#include "./ui_mainwindow.h"
/// header generated by qt


#include <QLabel> /// Include QLabel for updating text

/// constructor definition
MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent) /// initialize a widget parent
    , ui(new Ui::MainWindow) /// dynamically allocates an instance of this class and assigns it to ui variable

{
    ui->setupUi(this); /// function that sets up the user interface

    /// Connect the button's clicked() signal to a custom slot
    connect(ui->pushButton, &QPushButton::clicked, this, &MainWindow::startApp);
}

/// destructor definition
MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::startApp()
{
    /// Update the text of the label when the button is clicked
    ui->label->setText("QT App started");
}
